services:

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    env_file:
      - .env
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:17
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/maintz.sql:ro
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1;'"]
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 5s
